export const PRODUCT_INITIATE = "PRODUCT_INITIATE";
export const PRODUCT_SUCCESS = "PRODUCT_SUCCESS";
export const PRODUCT_FAILURE = "PRODUCT_FAILURE";
export const PRODUCT_REQUEST = "PRODUCT_REQUEST";
export const PRODUCT_SEARCH = "PRODUCT_SEARCH";
export const PRODUCT_FILTER = "PRODUCT_FILTER";
export const PRODUCT_ADDTOCART = "PRODUCT_ADDTOCART";
export const PRODUCT_ADDTOCART_STORAGE = "PRODUCT_ADDTOCART_STORAGE";
export const PRODUCT_CLEARCART = "PRODUCT_CLEARCART";



